/**
 * Seed comprehensive Nigerian foods — all major dishes by region.
 *
 * Usage:  npm run seed:nigeria
 */
import dotenv from 'dotenv';
dotenv.config();

import { db } from '../config/firebase.js';
import { COLLECTIONS } from '../config/constants.js';
import { formatFood } from '../models/Food.js';

// ─── Find Nigeria's doc ID ─────────────────────────────────────
const getNigeriaId = async () => {
  const snapshot = await db.collection(COLLECTIONS.COUNTRIES)
    .where('code', '==', 'NG')
    .limit(1)
    .get();
  if (snapshot.empty) throw new Error('Nigeria not found — run npm run seed:countries first');
  return { id: snapshot.docs[0].id, name: snapshot.docs[0].data().name };
};

// ─── Nigerian food data ────────────────────────────────────────
const makeFoods = (countryId, countryName) => [
  // ═══════════════════════════════════════════════════════════════
  //  SOUPS
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Egusi Soup',
    localName: 'Ofe Egusi',
    description: 'Rich melon-seed soup with leafy greens, assorted meat, and stockfish. The most popular soup across Nigeria.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 25, cookTime: 45, servings: 6,
    estimatedCost: '₦3,000–5,000',
    ingredients: ['2 cups ground egusi (melon seeds)', '500 g assorted meat (beef, tripe, cow skin)', '1 cup palm oil', '3 cups chopped spinach or bitter leaf', '2 scotch bonnet peppers', '1 large onion', '2 tbsp ground crayfish', 'Stockfish pieces', '2 seasoning cubes', 'Salt to taste'],
    instructions: ['Boil assorted meat with onion, seasoning cubes, and salt until tender. Reserve stock.', 'Heat palm oil in a pot (do not bleach).', 'Add diced onion and fry until translucent.', 'Mix ground egusi with a little water to form a thick paste.', 'Add egusi paste to oil in lumps. Fry for 5 minutes, stirring gently.', 'Pour in reserved meat stock gradually. Stir well.', 'Add ground crayfish, scotch bonnets, and cooked meat.', 'Simmer for 15 minutes on medium heat.', 'Add chopped spinach or washed bitter leaf. Cook 5 more minutes.', 'Adjust seasoning and serve with pounded yam, eba, or fufu.'],
    tags: ['egusi', 'soup', 'melon-seed', 'nationwide', 'pounded-yam'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/EGUSI.JPG/960px-EGUSI.JPG',
    isFeatured: true, rating: 4.9,
  },
  {
    name: 'Efo Riro',
    localName: 'Efo Riro',
    description: 'Yoruba-style rich vegetable soup made with assorted meats, locust beans, and a luscious palm oil base.',
    countryId, countryName,
    region: 'Southwest (Yoruba)',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 20, cookTime: 35, servings: 6,
    estimatedCost: '₦3,500–5,000',
    ingredients: ['1 large bunch spinach (efo tete or shoko)', '500 g assorted meat', '1/2 cup palm oil', '3 scotch bonnet peppers (blended)', '2 red bell peppers (blended)', '1 large onion', '2 tbsp locust beans (iru)', '2 tbsp ground crayfish', 'Stockfish / dry fish', '2 seasoning cubes', 'Salt'],
    instructions: ['Cook assorted meat until tender. Reserve stock.', 'Blanch spinach in boiling water for 1 minute. Drain and set aside.', 'Heat palm oil, fry onions until golden.', 'Add blended peppers and cook until oil floats on top.', 'Add locust beans, crayfish, and seasoning.', 'Pour in meat stock and add cooked meat/fish.', 'Simmer for 10 minutes.', 'Fold in the blanched vegetables. Cook 3–5 minutes.', 'Serve hot with amala, pounded yam, or eba.'],
    tags: ['efo-riro', 'vegetable-soup', 'yoruba', 'southwest'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Efo_Riro_with_fried_mackerel_fishes_and_roasted_cowskin.jpg/960px-Efo_Riro_with_fried_mackerel_fishes_and_roasted_cowskin.jpg',
    isFeatured: true, rating: 4.8,
  },
  {
    name: 'Ogbono Soup',
    localName: 'Ofe Ogbono',
    description: 'Draw soup made from ground ogbono (bush mango) seeds — silky, mucilaginous, and deeply flavoured.',
    countryId, countryName,
    region: 'Southeast / Nationwide',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 20, cookTime: 30, servings: 6,
    estimatedCost: '₦3,000–4,500',
    ingredients: ['2 cups ground ogbono seeds', '500 g assorted meat', '1/2 cup palm oil', '3 cups chopped spinach or okazi leaves', '2 scotch bonnet peppers', '1 large onion', '2 tbsp ground crayfish', 'Stockfish / dry fish', '2 seasoning cubes', 'Salt'],
    instructions: ['Boil assorted meat until tender. Reserve the stock.', 'Heat palm oil in a pot.', 'Add ground ogbono to the hot oil and fry, stirring constantly for 5 minutes until it dissolves.', 'Gradually add meat stock while stirring to prevent lumps.', 'Add blended pepper, crayfish, onion, and seasoning cubes.', 'Add cooked meat and fish. Simmer 15 minutes.', 'Stir in chopped vegetables. Cook 3 minutes.', 'Serve with eba, fufu, or pounded yam.'],
    tags: ['ogbono', 'draw-soup', 'bush-mango', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Ogbono_soup_with_assorted_meats.jpg',
    isFeatured: false, rating: 4.6,
  },
  {
    name: 'Ofe Nsala (White Soup)',
    localName: 'Ofe Nsala',
    description: 'Igbo white soup — a light, peppery catfish soup thickened with pounded yam, without palm oil.',
    countryId, countryName,
    region: 'Southeast (Igbo)',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 20, cookTime: 30, servings: 4,
    estimatedCost: '₦4,000–6,000',
    ingredients: ['1 whole catfish (cut into pieces)', '1 cup pounded yam (as thickener)', 'Utazi leaves', '2 scotch bonnet peppers', '1 onion', '2 tbsp ground crayfish', 'Uziza seeds (ground)', '1 seasoning cube', 'Salt'],
    instructions: ['Boil catfish with onion, seasoning, and salt for 10 minutes.', 'Remove fish and set aside.', 'Dissolve small lumps of pounded yam into the fish stock to thicken it.', 'Add ground uziza, crayfish, and scotch bonnet.', 'Return the fish to the pot.', 'Simmer for 10 minutes.', 'Add shredded utazi leaves in the last minute.', 'Serve with pounded yam or fufu.'],
    tags: ['nsala', 'white-soup', 'igbo', 'southeast', 'catfish'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Igbo_cuisine%2C_ofe_nsala.jpg/960px-Igbo_cuisine%2C_ofe_nsala.jpg',
    isFeatured: true, rating: 4.7,
  },
  {
    name: 'Ofe Onugbu (Bitter Leaf Soup)',
    localName: 'Ofe Onugbu',
    description: 'Igbo bitter leaf soup — hearty, earthy, and loaded with cocoyam thickener, meat, and stockfish.',
    countryId, countryName,
    region: 'Southeast (Igbo)',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'hard',
    prepTime: 40, cookTime: 50, servings: 6,
    estimatedCost: '₦4,000–6,000',
    ingredients: ['3 cups washed bitter leaves', '500 g assorted meat', '1 cup cocoyam paste (or achi)', '1/2 cup palm oil', '2 tbsp ground crayfish', 'Ogiri (locust bean paste)', 'Stockfish and dry fish', '2 scotch bonnet peppers', '2 seasoning cubes', 'Salt'],
    instructions: ['Wash bitter leaves thoroughly until the bitterness reduces. Squeeze dry.', 'Cook assorted meat, stockfish, and dry fish until tender.', 'Boil and pound cocoyam into smooth paste (or mix achi with water).', 'Add palm oil and cocoyam paste to the meat stock. Stir well.', 'Add ground crayfish, ogiri, and pepper.', 'Simmer 15 minutes until cocoyam dissolves and soup thickens.', 'Add the washed bitter leaves. Stir and cook 10 more minutes.', 'Serve with fufu or garri.'],
    tags: ['bitter-leaf', 'onugbu', 'igbo', 'southeast', 'cocoyam'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Bitterleaf_soup_%28_Nigerian_cuisine%29.jpg/960px-Bitterleaf_soup_%28_Nigerian_cuisine%29.jpg',
    isFeatured: false, rating: 4.6,
  },
  {
    name: 'Ofe Oha',
    localName: 'Ofe Oha',
    description: 'Traditional Igbo soup made with tender oha leaves, cocoyam, and assorted proteins — fragrant and earthy.',
    countryId, countryName,
    region: 'Southeast (Igbo)',
    categories: ['lunch', 'dinner', 'traditional', 'festive'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 30, cookTime: 40, servings: 6,
    estimatedCost: '₦4,500–6,500',
    ingredients: ['2 cups oha leaves (shredded by hand)', '500 g assorted meat', '1 cup cocoyam paste', '1/2 cup palm oil', '2 tbsp ground crayfish', 'Ogiri', 'Stockfish', '2 scotch bonnet peppers', 'Seasoning cubes', 'Salt'],
    instructions: ['Cook assorted meat with stockfish until tender. Reserve stock.', 'Prepare cocoyam paste by boiling and pounding cocoyam.', 'Add palm oil and cocoyam to the stock. Stir to dissolve.', 'Add crayfish, ogiri, pepper, and seasoning. Simmer 15 minutes.', 'When soup thickens, add meat and fish.', 'Shred oha leaves by hand (do not cut with knife) and stir in.', 'Cook 5 minutes. Do not overcook the leaves.', 'Serve with fufu, eba, or pounded yam.'],
    tags: ['oha', 'igbo', 'southeast', 'traditional', 'cocoyam'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/85/OhaSoup.jpg',
    isFeatured: false, rating: 4.5,
  },
  {
    name: 'Ofe Akwu (Banga Soup)',
    localName: 'Ofe Akwu / Banga',
    description: 'Palm fruit cream soup — rich, creamy, and aromatic. Called Banga in Delta and Ofe Akwu in Igboland.',
    countryId, countryName,
    region: 'South-South / Southeast',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'hard',
    prepTime: 30, cookTime: 50, servings: 6,
    estimatedCost: '₦3,500–5,500',
    ingredients: ['2 kg palm fruits', '500 g assorted meat or fresh fish', 'Banga spice (obrunbebe stick, rohojie, oburunbebe)', '2 scotch bonnet peppers', '1 onion', '2 tbsp ground crayfish', 'Dry fish / stockfish', 'Seasoning cubes', 'Salt'],
    instructions: ['Boil palm fruits until soft. Pound in mortar and extract the cream with warm water.', 'Sieve to get smooth palm cream. Discard chaff.', 'Cook assorted meat until tender.', 'Pour palm cream into a pot and bring to a boil, stirring often.', 'Add banga spices, pepper, crayfish, and seasoning.', 'Add cooked meat and fish.', 'Simmer until the oil rises and soup thickens (about 25 minutes).', 'Serve with starch, eba, or white rice.'],
    tags: ['banga', 'ofe-akwu', 'palm-fruit', 'south-south', 'delta'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Eba_served_with_Fresh_fish_banga_soup_in_a_clay_pot.jpg/960px-Eba_served_with_Fresh_fish_banga_soup_in_a_clay_pot.jpg',
    isFeatured: true, rating: 4.7,
  },
  {
    name: 'Afang Soup',
    localName: 'Afang',
    description: 'Calabar delicacy made with shredded afang (okazi) leaves and waterleaf — rich, green, and loaded with protein.',
    countryId, countryName,
    region: 'South-South (Cross River / Akwa Ibom)',
    categories: ['lunch', 'dinner', 'traditional', 'festive'],
    targetAudience: ['everyone'],
    difficulty: 'hard',
    prepTime: 40, cookTime: 40, servings: 6,
    estimatedCost: '₦5,000–8,000',
    ingredients: ['3 cups shredded afang leaves', '4 cups chopped waterleaf', '500 g assorted meat', '1 cup periwinkle (optional)', '1/2 cup palm oil', '3 tbsp ground crayfish', 'Stockfish and dry fish', '2 scotch bonnet peppers', 'Seasoning cubes', 'Salt'],
    instructions: ['Cook assorted meat, stockfish, and periwinkle until tender.', 'Blanch waterleaf until it reduces by half. Set aside.', 'Shred the afang leaves very finely (the finer the better).', 'Heat palm oil. Add pepper, crayfish, and seasoning.', 'Add meat stock and cooked proteins.', 'Add the waterleaf and simmer 10 minutes.', 'Add shredded afang leaves last. Stir and cook 5 minutes.', 'Serve with eba, fufu, or pounded yam.'],
    tags: ['afang', 'calabar', 'cross-river', 'south-south', 'waterleaf'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Uqwu_Afang_soup_07.jpg/960px-Uqwu_Afang_soup_07.jpg',
    isFeatured: true, rating: 4.8,
  },
  {
    name: 'Edikang Ikong',
    localName: 'Edikang Ikong',
    description: 'The king of Efik soups — a luxurious mix of fluted pumpkin leaves (ugu) and waterleaf, packed with assorted meats and seafood.',
    countryId, countryName,
    region: 'South-South (Cross River / Akwa Ibom)',
    categories: ['lunch', 'dinner', 'traditional', 'festive'],
    targetAudience: ['everyone'],
    difficulty: 'hard',
    prepTime: 40, cookTime: 40, servings: 6,
    estimatedCost: '₦6,000–10,000',
    ingredients: ['3 cups shredded ugu (pumpkin leaves)', '3 cups chopped waterleaf', '500 g assorted meat', '200 g prawns / shrimp', '200 g periwinkle', '1/2 cup palm oil', '3 tbsp ground crayfish', 'Stockfish and dry fish', '2 scotch bonnet peppers', 'Seasoning cubes', 'Salt'],
    instructions: ['Cook assorted meat and seafood until tender.', 'Shred ugu leaves finely. Chop waterleaf.', 'Blanch waterleaf until it reduces. Squeeze out excess water.', 'Heat palm oil. Add diced onions and fry.', 'Add pepper, crayfish, seasoning, and meat stock.', 'Add all cooked proteins, periwinkle, and prawns.', 'Add waterleaf first, cook 5 minutes.', 'Add ugu leaves last. Stir gently and cook 3 minutes.', 'Serve with eba or fufu.'],
    tags: ['edikang-ikong', 'efik', 'calabar', 'south-south', 'ugu'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Edikang_ikong.jpg',
    isFeatured: true, rating: 4.9,
  },
  {
    name: 'Gbegiri Soup',
    localName: 'Gbegiri',
    description: 'Yoruba bean soup — smooth, creamy, and always paired with ewedu and stew to create the classic "abula" combo.',
    countryId, countryName,
    region: 'Southwest (Yoruba)',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'easy',
    prepTime: 15, cookTime: 30, servings: 4,
    estimatedCost: '₦1,500–2,500',
    ingredients: ['2 cups peeled beans (honey beans)', '1/2 cup palm oil', '1 onion', '2 scotch bonnet peppers', '1 tbsp ground crayfish', '1 seasoning cube', 'Salt'],
    instructions: ['Boil peeled beans until very soft and falling apart.', 'Blend the cooked beans until smooth.', 'Pour back into pot. Add palm oil, blended pepper, and crayfish.', 'Add seasoning and salt. Stir well.', 'Simmer on low heat for 15 minutes until thick and creamy.', 'Serve alongside ewedu and pepper stew over amala.'],
    tags: ['gbegiri', 'bean-soup', 'yoruba', 'southwest', 'abula'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Yoruba_delicacies.jpg/960px-Yoruba_delicacies.jpg',
    isFeatured: false, rating: 4.5,
  },
  {
    name: 'Ewedu Soup',
    localName: 'Ewedu',
    description: 'Silky jute leaf soup — a Yoruba staple always served with gbegiri and stew on amala.',
    countryId, countryName,
    region: 'Southwest (Yoruba)',
    categories: ['lunch', 'dinner', 'traditional', 'budget-friendly'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 10, cookTime: 15, servings: 4,
    estimatedCost: '₦500–1,000',
    ingredients: ['2 bunches ewedu (jute) leaves', '1 tsp potash (kaun) or baking soda', '1 locust bean (iru)', '1 seasoning cube', 'Salt'],
    instructions: ['Pick ewedu leaves from stems. Wash thoroughly.', 'Boil with a pinch of potash for 5 minutes until soft.', 'Use a broom whisk (ijabe) or blender to break down the leaves.', 'Add locust beans and seasoning. Stir.', 'Simmer 5 minutes until slimy and smooth.', 'Serve alongside gbegiri and stew over amala.'],
    tags: ['ewedu', 'jute-leaf', 'yoruba', 'southwest', 'abula'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Amala_and_Gbegiri_with_Ewedu_soup.jpg',
    isFeatured: false, rating: 4.4,
  },
  {
    name: 'Miyan Kuka (Baobab Soup)',
    localName: 'Miyan Kuka',
    description: 'Northern Nigerian baobab leaf soup — slightly sour, slimy, and perfect with tuwo shinkafa.',
    countryId, countryName,
    region: 'North (Hausa)',
    categories: ['lunch', 'dinner', 'traditional', 'budget-friendly'],
    targetAudience: ['everyone'],
    difficulty: 'easy',
    prepTime: 10, cookTime: 20, servings: 4,
    estimatedCost: '₦800–1,500',
    ingredients: ['1 cup kuka (baobab) powder', '500 g beef or goat meat', '2 tbsp groundnut oil', '1 onion', '2 scotch bonnet peppers', '1 tbsp dawadawa (locust beans)', '1 seasoning cube', 'Salt'],
    instructions: ['Cook meat with onion and seasoning until tender. Reserve stock.', 'Dissolve kuka powder in warm water to a smooth paste.', 'Bring meat stock to a boil.', 'Stir in the kuka paste. Mix thoroughly to avoid lumps.', 'Add dawadawa, pepper, and oil.', 'Simmer for 10 minutes.', 'Serve hot over tuwo shinkafa or tuwo masara.'],
    tags: ['kuka', 'baobab', 'hausa', 'north', 'tuwo'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Tuwo_with_miyan_kuka_and_fried_fish.jpg/960px-Tuwo_with_miyan_kuka_and_fried_fish.jpg',
    isFeatured: false, rating: 4.3,
  },
  {
    name: 'Miyan Taushe (Pumpkin Soup)',
    localName: 'Miyan Taushe',
    description: 'Northern Nigerian pumpkin soup — thick, orange, and nutty with ground groundnuts. A Hausa classic.',
    countryId, countryName,
    region: 'North (Hausa)',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 20, cookTime: 35, servings: 6,
    estimatedCost: '₦1,500–2,500',
    ingredients: ['500 g pumpkin (peeled and cubed)', '1 cup groundnut paste', '500 g beef', 'Spinach or sorrel leaves', '2 scotch bonnet peppers', '1 onion', '2 tbsp groundnut oil', 'Dawadawa', '1 seasoning cube', 'Salt'],
    instructions: ['Cook beef with onion and seasoning until tender.', 'Add pumpkin cubes to the stock. Boil until soft.', 'Mash or blend the pumpkin into the stock.', 'Add groundnut paste and stir to combine.', 'Add dawadawa, pepper, and oil. Simmer 15 minutes.', 'Add chopped spinach or sorrel. Cook 5 minutes.', 'Serve with tuwo shinkafa or tuwo masara.'],
    tags: ['taushe', 'pumpkin', 'groundnut', 'hausa', 'north'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Food_in_Abuja_10.jpg/960px-Food_in_Abuja_10.jpg',
    isFeatured: false, rating: 4.4,
  },
  {
    name: 'Pepper Soup',
    localName: 'Pepper Soup',
    description: 'Fiery, aromatic broth made with goat meat, catfish, or assorted meat — Nigeria\'s favourite cold-weather cure.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['dinner', 'street-food', 'traditional'],
    targetAudience: ['young-professionals', 'everyone'],
    difficulty: 'easy',
    prepTime: 15, cookTime: 40, servings: 4,
    estimatedCost: '₦3,000–5,000',
    ingredients: ['1 kg goat meat or catfish', '2 tbsp pepper soup spice mix', '3 scotch bonnet peppers', '1 onion', '2 cloves garlic', '1 tbsp grated ginger', 'Scent leaves (nchuanwu)', 'Utazi leaves', '2 seasoning cubes', 'Salt'],
    instructions: ['Wash and season meat/fish with salt and seasoning.', 'Add to a pot with water, onion, garlic, and ginger.', 'Boil until meat is tender (about 30 minutes for goat meat).', 'Add pepper soup spice and scotch bonnets.', 'Simmer for 10 more minutes.', 'Add torn scent leaves and utazi in the last minute.', 'Serve hot in a bowl. Perfect with chilled drinks.'],
    tags: ['pepper-soup', 'goat', 'catfish', 'spicy', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Red_pepper_and_tomato_soup%2C_with_chicken%2C_wild_rice%2C_and_black_pepper_-_Massachusetts.jpg/960px-Red_pepper_and_tomato_soup%2C_with_chicken%2C_wild_rice%2C_and_black_pepper_-_Massachusetts.jpg',
    isFeatured: true, rating: 4.8,
  },
  {
    name: 'Okro Soup (Ila Asepo)',
    localName: 'Ila Asepo',
    description: 'Fresh okra soup — slimy, flavourful, and loaded with assorted proteins. Cooked Yoruba-style with palm oil and locust beans.',
    countryId, countryName,
    region: 'Southwest (Yoruba) / Nationwide',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'easy',
    prepTime: 20, cookTime: 25, servings: 6,
    estimatedCost: '₦2,500–4,000',
    ingredients: ['30 fresh okra fingers (chopped)', '500 g assorted meat', '1/2 cup palm oil', '2 tbsp ground crayfish', 'Iru (locust beans)', '2 scotch bonnet peppers', '1 onion', 'Stockfish / dry fish', '2 seasoning cubes', 'Salt'],
    instructions: ['Cook assorted meat until tender. Reserve stock.', 'Chop okra into small pieces (or grate for smoother texture).', 'Heat palm oil. Add onions and fry.', 'Add blended pepper, crayfish, iru, and seasoning.', 'Pour in meat stock. Add cooked meat and fish.', 'Bring to a boil, then add chopped okra.', 'Stir and cook for 5–7 minutes. Do not overcook.', 'Serve with eba, amala, or pounded yam.'],
    tags: ['okro', 'okra', 'ila', 'yoruba', 'southwest', 'slimy'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Red_pepper_and_tomato_soup%2C_with_chicken%2C_wild_rice%2C_and_black_pepper_-_Massachusetts.jpg/960px-Red_pepper_and_tomato_soup%2C_with_chicken%2C_wild_rice%2C_and_black_pepper_-_Massachusetts.jpg',
    isFeatured: false, rating: 4.5,
  },
  {
    name: 'Fisherman Soup',
    localName: 'Fisherman Soup',
    description: 'South-South seafood extravaganza — a rich, peppery broth teeming with fresh fish, prawns, crabs, and periwinkle.',
    countryId, countryName,
    region: 'South-South (Rivers / Bayelsa)',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 25, cookTime: 35, servings: 4,
    estimatedCost: '₦5,000–8,000',
    ingredients: ['1 whole catfish', '200 g prawns', '4 fresh crabs', 'Periwinkle', '2 cups palm oil', '3 scotch bonnet peppers', '1 onion', '3 tbsp ground crayfish', 'Scent leaves', '2 seasoning cubes', 'Salt'],
    instructions: ['Clean and cut catfish. Season with salt.', 'Boil crabs and periwinkle separately.', 'In a pot, heat palm oil. Add onion and pepper.', 'Add crayfish and seasoning. Fry 5 minutes.', 'Add water/stock and bring to a boil.', 'Add fish, crabs, prawns, and periwinkle.', 'Simmer gently for 15–20 minutes.', 'Add scent leaves in the last minute.', 'Serve with white rice or eba.'],
    tags: ['fisherman', 'seafood', 'south-south', 'rivers', 'bayelsa'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Red_pepper_and_tomato_soup%2C_with_chicken%2C_wild_rice%2C_and_black_pepper_-_Massachusetts.jpg/960px-Red_pepper_and_tomato_soup%2C_with_chicken%2C_wild_rice%2C_and_black_pepper_-_Massachusetts.jpg',
    isFeatured: false, rating: 4.6,
  },
  {
    name: 'Ekpang Nkukwo',
    localName: 'Ekpang Nkukwo',
    description: 'Efik delicacy of grated cocoyam and water yam wrapped in cocoyam leaves, cooked in a spiced palm oil broth.',
    countryId, countryName,
    region: 'South-South (Cross River / Akwa Ibom)',
    categories: ['lunch', 'dinner', 'traditional', 'festive'],
    targetAudience: ['everyone'],
    difficulty: 'hard',
    prepTime: 60, cookTime: 45, servings: 6,
    estimatedCost: '₦4,000–6,000',
    ingredients: ['2 kg cocoyam', '1 kg water yam', 'Cocoyam leaves (or spinach)', '500 g smoked fish', '200 g periwinkle', '1 cup palm oil', '3 tbsp ground crayfish', '3 scotch bonnet peppers', '2 seasoning cubes', 'Salt'],
    instructions: ['Peel and grate cocoyam and water yam separately.', 'Mix both grated tubers together.', 'Wrap small portions in cocoyam leaves to form parcels.', 'Arrange parcels in a pot.', 'Add palm oil, crayfish, pepper, seasoning, and water.', 'Add smoked fish and periwinkle between the parcels.', 'Cook on medium heat for 40–45 minutes until done.', 'Serve hot directly from the pot.'],
    tags: ['ekpang-nkukwo', 'cocoyam', 'efik', 'calabar', 'south-south'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Edikang_ikong.jpg',
    isFeatured: false, rating: 4.5,
  },

  // ═══════════════════════════════════════════════════════════════
  //  RICE DISHES
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Jollof Rice',
    localName: 'Jollof',
    description: 'Nigeria\'s pride — smoky one-pot tomato rice cooked to perfection. Party jollof with the bottom-pot "sóòsì" is unmatched.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['lunch', 'dinner', 'traditional', 'budget-friendly'],
    targetAudience: ['university-students', 'young-professionals', 'everyone'],
    difficulty: 'medium',
    prepTime: 20, cookTime: 45, servings: 8,
    estimatedCost: '₦3,000–5,000',
    ingredients: ['4 cups long-grain rice', '8 Roma tomatoes', '4 red bell peppers (tatashe)', '4 scotch bonnet peppers', '2 large onions', '1/2 cup vegetable oil', '3 tbsp tomato paste', '2 tsp curry powder', '1 tsp thyme', '2 bay leaves', '4 cups chicken stock', 'Salt to taste', 'Seasoning cubes'],
    instructions: ['Blend tomatoes, tatashe, and scotch bonnets until smooth.', 'Heat oil in a heavy-bottom pot. Fry diced onion until golden.', 'Add tomato paste and fry for 2 minutes.', 'Pour in blended pepper mix. Cook on medium heat, stirring regularly, until oil floats (about 30 minutes).', 'Add curry, thyme, bay leaves, stock, and salt.', 'Wash rice thoroughly and add to the pot. Stir once.', 'Cover tightly with foil, then the lid. Cook on low heat for 30 minutes.', 'Do NOT open the lid. Let it steam.', 'Fluff with a fork. Serve with fried plantain and coleslaw.'],
    tags: ['jollof', 'rice', 'party', 'nationwide', 'smoky'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Jollof_Rice_with_Stew.jpg/960px-Jollof_Rice_with_Stew.jpg',
    isFeatured: true, rating: 4.9,
  },
  {
    name: 'Fried Rice',
    localName: 'Fried Rice',
    description: 'Nigerian-style fried rice loaded with mixed vegetables, liver, and shrimp — a party staple served alongside jollof.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['lunch', 'dinner', 'festive'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 30, cookTime: 30, servings: 8,
    estimatedCost: '₦3,500–5,500',
    ingredients: ['4 cups long-grain rice', '1 cup mixed vegetables (carrots, green beans, peas, sweetcorn)', '200 g beef liver', '200 g prawns', '3 eggs', '1/2 cup vegetable oil', '1 onion', '1 tsp curry powder', '1 tsp thyme', '2 seasoning cubes', 'Salt', 'Green bell pepper'],
    instructions: ['Parboil rice until 70% done. Drain and rinse.', 'Season and fry liver. Cut into small pieces.', 'Season and stir-fry prawns. Set aside.', 'Scramble eggs and cut into strips.', 'Dice all vegetables into small uniform pieces.', 'Heat oil in a large pan. Fry onions, then add vegetables.', 'Add the parboiled rice. Stir well.', 'Season with curry, thyme, seasoning cubes, and salt.', 'Add liver, prawns, and egg strips. Toss to combine.', 'Serve alongside jollof rice at parties.'],
    tags: ['fried-rice', 'party', 'vegetables', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Koh_Mak%2C_Thailand%2C_Fried_rice_with_seafood%2C_Thai_fried_rice.jpg/960px-Koh_Mak%2C_Thailand%2C_Fried_rice_with_seafood%2C_Thai_fried_rice.jpg',
    isFeatured: true, rating: 4.7,
  },
  {
    name: 'Ofada Rice & Ayamase Stew',
    localName: 'Ofada / Ayamase',
    description: 'Aromatic unpolished local rice served with spicy green pepper stew (ayamase / designer stew) — a Yoruba luxury.',
    countryId, countryName,
    region: 'Southwest (Yoruba)',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['young-professionals', 'everyone'],
    difficulty: 'medium',
    prepTime: 20, cookTime: 40, servings: 4,
    estimatedCost: '₦2,500–4,000',
    ingredients: ['3 cups ofada rice', '10 green bell peppers (rodo)', '5 scotch bonnet peppers', '1 cup palm oil (bleached)', '3 onions', '200 g assorted meat', '100 g ponmo (cow skin)', '2 boiled eggs', 'Iru (locust beans)', 'Seasoning cubes', 'Salt', 'Crayfish'],
    instructions: ['Wash ofada rice thoroughly in multiple changes of water.', 'Cook until soft. Drain and set aside.', 'Boil green peppers and scotch bonnets. Blend coarsely.', 'Bleach palm oil (heat until it turns clear). Let it cool slightly.', 'Fry diced onions in the oil until brown.', 'Add blended pepper mix. Cook until oil floats.', 'Add iru, crayfish, seasoning, and salt.', 'Add cooked meat, ponmo, and boiled eggs. Simmer 15 minutes.', 'Wrap ofada rice in banana leaf (uma). Serve with ayamase.'],
    tags: ['ofada', 'ayamase', 'green-pepper', 'designer-stew', 'yoruba'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Ofada_rise_with_fried_plantain_and_beaf.jpg',
    isFeatured: true, rating: 4.8,
  },
  {
    name: 'Coconut Rice',
    localName: 'Coconut Rice',
    description: 'Fragrant, creamy rice cooked in coconut milk — a Southern Nigerian twist on everyday rice.',
    countryId, countryName,
    region: 'South-South / Southwest',
    categories: ['lunch', 'dinner', 'quick-meals'],
    targetAudience: ['university-students', 'young-professionals', 'everyone'],
    difficulty: 'easy',
    prepTime: 10, cookTime: 30, servings: 4,
    estimatedCost: '₦2,000–3,000',
    ingredients: ['3 cups rice', '2 cups coconut milk', '1 cup water', '1 red bell pepper', '1 scotch bonnet', '1 onion', '2 tbsp vegetable oil', '1 tsp curry powder', 'Salt', 'Seasoning cube'],
    instructions: ['Parboil rice until half done. Drain.', 'Blend pepper and onion.', 'Fry blended pepper in oil until reduced.', 'Add coconut milk and water. Bring to a boil.', 'Add rice, curry, seasoning, and salt.', 'Cover tightly and cook on low heat until rice absorbs all liquid.', 'Fluff and serve with fried plantain or chicken.'],
    tags: ['coconut', 'rice', 'creamy', 'south-south'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Nasi_Liwet_Solo.jpg/960px-Nasi_Liwet_Solo.jpg',
    isFeatured: false, rating: 4.5,
  },
  {
    name: 'Native Jollof (Iwuk Edesi)',
    localName: 'Iwuk Edesi',
    description: 'South-South palm oil jollof with crayfish and dry fish — darker, richer, and more intensely flavoured than regular jollof.',
    countryId, countryName,
    region: 'South-South (Akwa Ibom / Cross River)',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 20, cookTime: 40, servings: 6,
    estimatedCost: '₦2,500–4,000',
    ingredients: ['3 cups rice', '1 cup palm oil', '3 tbsp ground crayfish', 'Smoked fish / dry fish', '2 scotch bonnet peppers', '1 onion', 'Scent leaves', '2 seasoning cubes', 'Salt'],
    instructions: ['Parboil rice. Drain.', 'Heat palm oil. Fry onion and pepper.', 'Add crayfish and seasoning.', 'Add water/stock and bring to a boil.', 'Add rice. Cover and cook on low heat until done.', 'Add smoked fish and scent leaves in the last 5 minutes.', 'Serve hot.'],
    tags: ['native-jollof', 'palm-oil', 'south-south', 'akwa-ibom'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Jollof_Rice_with_Stew.jpg/960px-Jollof_Rice_with_Stew.jpg',
    isFeatured: false, rating: 4.5,
  },
  {
    name: 'Tuwo Shinkafa',
    localName: 'Tuwo Shinkafa',
    description: 'Northern Nigerian rice pudding — soft, smooth, and moulded into balls. The rice version of swallow, served with miyan kuka or taushe.',
    countryId, countryName,
    region: 'North (Hausa)',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'easy',
    prepTime: 5, cookTime: 25, servings: 4,
    estimatedCost: '₦500–1,000',
    ingredients: ['2 cups short-grain rice (or rice flour)', 'Water', 'Pinch of salt'],
    instructions: ['Wash rice and boil with plenty of water until overcooked and mushy.', 'Mash the rice vigorously with a wooden spoon until smooth and stretchy.', 'Alternatively, mix rice flour with water and stir over heat.', 'Keep stirring until it forms a thick, smooth dough.', 'Mould into balls with a wet spoon.', 'Serve with miyan kuka, taushe, or miyan kubewa.'],
    tags: ['tuwo', 'shinkafa', 'rice-swallow', 'hausa', 'north'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/A_picture_of_a_lady_eating_Tuwo_Shinkafa.jpg/960px-A_picture_of_a_lady_eating_Tuwo_Shinkafa.jpg',
    isFeatured: false, rating: 4.3,
  },

  // ═══════════════════════════════════════════════════════════════
  //  SWALLOWS & STAPLES
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Pounded Yam',
    localName: 'Iyan',
    description: 'The king of swallow — smooth, stretchy yam dough pounded in a mortar until cloud-soft. The ultimate Nigerian comfort food.',
    countryId, countryName,
    region: 'Southwest / Southeast / Nationwide',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 10, cookTime: 30, servings: 4,
    estimatedCost: '₦2,000–3,000',
    ingredients: ['2 medium yam tubers', 'Water'],
    instructions: ['Peel yam and cut into medium chunks.', 'Boil in water until very soft (fork-tender).', 'Drain most water. Begin pounding in a mortar with a pestle.', 'Pound continuously, adding small splashes of water, until smooth and stretchy.', 'Alternatively, use a yam pounder machine.', 'Mould into smooth balls.', 'Serve with egusi, efo riro, ogbono, or ofe nsala.'],
    tags: ['pounded-yam', 'iyan', 'swallow', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Iyan_%26_Efo-Riro_%287370530836%29.jpg/960px-Iyan_%26_Efo-Riro_%287370530836%29.jpg',
    isFeatured: true, rating: 4.9,
  },
  {
    name: 'Amala',
    localName: 'Amala',
    description: 'Dark, smooth yam flour swallow — the Yoruba answer to pounded yam. Served with ewedu, gbegiri, and stew (abula).',
    countryId, countryName,
    region: 'Southwest (Yoruba)',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 5, cookTime: 10, servings: 4,
    estimatedCost: '₦500–1,000',
    ingredients: ['2 cups amala flour (yam flour / elubo)', 'Boiling water'],
    instructions: ['Boil water in a pot.', 'Reduce heat. Gradually pour amala flour into the water while stirring with a wooden spatula.', 'Stir vigorously to prevent lumps.', 'Keep stirring on low heat until the mixture is smooth and firm.', 'Mould into a round shape.', 'Serve with ewedu + gbegiri + stew (abula) or any Nigerian soup.'],
    tags: ['amala', 'yam-flour', 'swallow', 'yoruba', 'southwest', 'abula'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Amala_with_Ewedu.jpg/960px-Amala_with_Ewedu.jpg',
    isFeatured: true, rating: 4.7,
  },
  {
    name: 'Eba (Garri)',
    localName: 'Eba',
    description: 'Cassava flour (garri) mixed with hot water to form a stretchy dough — the quickest and most affordable swallow in Nigeria.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['lunch', 'dinner', 'traditional', 'budget-friendly', 'quick-meals'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 2, cookTime: 5, servings: 2,
    estimatedCost: '₦200–500',
    ingredients: ['1 cup garri (cassava flakes)', 'Boiling water'],
    instructions: ['Boil water in a kettle.', 'Pour garri into a bowl.', 'Add hot water gradually while stirring with a wooden spoon.', 'Stir quickly and firmly until it forms a smooth, stretchy dough.', 'Mould into a ball.', 'Serve immediately with any soup of choice.'],
    tags: ['eba', 'garri', 'cassava', 'swallow', 'nationwide', 'budget'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Garri_flour.jpg',
    isFeatured: false, rating: 4.3,
  },
  {
    name: 'Fufu (Akpu)',
    localName: 'Akpu / Fufu',
    description: 'Fermented cassava swallow — smooth, slightly tangy, and stretchy. A staple in Southeast and South-South Nigeria.',
    countryId, countryName,
    region: 'Southeast / South-South',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'easy',
    prepTime: 5, cookTime: 15, servings: 4,
    estimatedCost: '₦300–800',
    ingredients: ['2 cups fermented cassava (or fufu flour)', 'Boiling water'],
    instructions: ['If using fresh: soak cassava for 3 days until fermented, then sieve.', 'If using flour: mix fufu flour with cold water to a smooth paste.', 'Bring a pot of water to a boil.', 'Add the paste and stir vigorously on heat.', 'Keep stirring until smooth, firm, and stretchy.', 'Mould into balls.', 'Serve with egusi, oha, bitter leaf, or ogbono soup.'],
    tags: ['fufu', 'akpu', 'cassava', 'swallow', 'southeast', 'fermented'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Wrapped_fufu.jpg',
    isFeatured: false, rating: 4.4,
  },

  // ═══════════════════════════════════════════════════════════════
  //  STREET FOOD & SNACKS
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Suya',
    localName: 'Tsire',
    description: 'Spicy grilled beef skewers coated in yaji (peanut spice mix) — Nigeria\'s king of street food, best at night from the mallam\'s grill.',
    countryId, countryName,
    region: 'North (Hausa) / Nationwide',
    categories: ['street-food', 'snacks', 'dinner', 'quick-meals'],
    targetAudience: ['university-students', 'young-professionals', 'everyone'],
    difficulty: 'easy',
    prepTime: 30, cookTime: 15, servings: 4,
    estimatedCost: '₦1,000–2,000',
    ingredients: ['500 g beef sirloin (thinly sliced)', '1/2 cup yaji spice (groundnuts, ginger, paprika, cayenne, onion powder)', '2 tbsp vegetable oil', '1 large onion (sliced)', 'Tomatoes (sliced)', 'Cabbage (shredded)', 'Newspaper/foil for wrapping', 'Wooden skewers', 'Salt'],
    instructions: ['Soak wooden skewers in water for 30 minutes.', 'Slice beef very thinly against the grain.', 'Rub with oil, salt, and half the yaji spice.', 'Thread onto skewers.', 'Grill over charcoal, turning frequently, for 5–7 minutes per side.', 'Sprinkle remaining yaji generously over hot skewers.', 'Wrap in newspaper with sliced onions, tomatoes, and cabbage.', 'Squeeze fresh lemon on top. Eat immediately.'],
    tags: ['suya', 'yaji', 'grill', 'street-food', 'hausa', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/SuyavarietiesTX.JPG/960px-SuyavarietiesTX.JPG',
    isFeatured: true, rating: 4.9,
  },
  {
    name: 'Akara (Bean Cakes)',
    localName: 'Akara / Kosai',
    description: 'Deep-fried bean cakes — crispy outside, fluffy inside. The ultimate Nigerian breakfast, best with pap or bread.',
    countryId, countryName,
    region: 'Southwest (Yoruba) / Nationwide',
    categories: ['breakfast', 'street-food', 'snacks', 'budget-friendly'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 20, cookTime: 15, servings: 4,
    estimatedCost: '₦500–1,000',
    ingredients: ['2 cups peeled beans (honey beans or black-eyed peas)', '1 red bell pepper', '1 scotch bonnet pepper', '1 small onion', 'Salt to taste', 'Vegetable oil for deep frying'],
    instructions: ['Soak beans for 1 hour, then rub to remove skins. Rinse.', 'Blend beans with pepper and onion to a thick, smooth batter. Do NOT add water.', 'Season with salt. Whisk the batter vigorously to incorporate air (makes it fluffy).', 'Heat oil in a deep pan to 350°F.', 'Scoop batter with a spoon and drop into hot oil.', 'Fry until golden brown on all sides (3–4 minutes).', 'Drain on paper towels.', 'Serve hot with pap (ogi), bread, or garri.'],
    tags: ['akara', 'kosai', 'bean-cake', 'breakfast', 'street-food'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Beans_Ball-Akara.jpg',
    isFeatured: true, rating: 4.7,
  },
  {
    name: 'Moi Moi (Bean Pudding)',
    localName: 'Moi Moi / Moin Moin',
    description: 'Steamed bean pudding made from blended peeled beans — soft, savoury, and often stuffed with eggs and fish.',
    countryId, countryName,
    region: 'Southwest (Yoruba) / Nationwide',
    categories: ['breakfast', 'lunch', 'snacks', 'traditional'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'medium',
    prepTime: 30, cookTime: 45, servings: 8,
    estimatedCost: '₦1,500–2,500',
    ingredients: ['3 cups peeled beans', '4 red bell peppers', '3 scotch bonnet peppers', '2 onions', '1/2 cup vegetable oil', '4 boiled eggs (optional)', 'Sardines or corned beef (optional)', 'Ground crayfish', '2 seasoning cubes', 'Salt', 'Uma (moi moi leaves) or aluminium cups'],
    instructions: ['Soak beans, remove skins, and blend until smooth with peppers and onion.', 'Add oil, crayfish, seasoning, and salt. Mix well.', 'The batter should be pourable but not too thin.', 'Grease cups or line with leaves. Pour in batter.', 'Add boiled egg halves or sardines into each cup (optional).', 'Steam in a pot with water for 40–45 minutes.', 'Check with a toothpick — it should come out clean.', 'Serve with jollof rice, custard, or pap.'],
    tags: ['moi-moi', 'bean-pudding', 'steamed', 'nationwide', 'breakfast'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Moin_Moin.jpg/960px-Moin_Moin.jpg',
    isFeatured: true, rating: 4.8,
  },
  {
    name: 'Puff Puff',
    localName: 'Puff Puff',
    description: 'Deep-fried dough balls — pillowy, sweet, and irresistible. Nigeria\'s answer to doughnuts.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['snacks', 'street-food', 'breakfast', 'desserts'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 90, cookTime: 15, servings: 6,
    estimatedCost: '₦500–1,000',
    ingredients: ['3 cups all-purpose flour', '1/2 cup sugar', '1 tsp yeast', '1/2 tsp nutmeg', 'Warm water', 'Pinch of salt', 'Vegetable oil for deep frying'],
    instructions: ['Mix flour, sugar, yeast, nutmeg, and salt.', 'Add warm water gradually and mix to a smooth, thick batter.', 'Cover and let rise in a warm place for 1–2 hours until doubled.', 'Heat oil to 350°F.', 'Scoop batter with wet hands or a spoon and drop into oil.', 'Fry, turning occasionally, until golden all over (3–4 minutes).', 'Drain on paper towels. Dust with powdered sugar (optional).', 'Serve warm.'],
    tags: ['puff-puff', 'doughnut', 'fried', 'snack', 'sweet', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Nigerian-puff-puff-recipe_cropped.jpg',
    isFeatured: true, rating: 4.7,
  },
  {
    name: 'Chin Chin',
    localName: 'Chin Chin',
    description: 'Crunchy fried pastry bites — sweet, addictive, and ever-present at Nigerian celebrations.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['snacks', 'desserts'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 20, cookTime: 15, servings: 8,
    estimatedCost: '₦500–1,000',
    ingredients: ['4 cups all-purpose flour', '1/2 cup sugar', '1/4 cup butter (softened)', '2 eggs', '1/2 cup milk', '1/2 tsp nutmeg', '1/2 tsp baking powder', 'Pinch of salt', 'Vegetable oil for frying'],
    instructions: ['Mix flour, sugar, nutmeg, baking powder, and salt.', 'Rub in butter until mixture resembles breadcrumbs.', 'Beat eggs with milk. Add to flour mixture.', 'Knead into a smooth, firm dough.', 'Roll out on a floured surface and cut into small strips or squares.', 'Deep fry in batches on medium heat until golden (5–6 minutes).', 'Drain and cool completely. Store in airtight container.'],
    tags: ['chin-chin', 'pastry', 'fried', 'celebration', 'snack', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/LoveChinChin.jpg/960px-LoveChinChin.jpg',
    isFeatured: false, rating: 4.5,
  },
  {
    name: 'Dodo (Fried Plantain)',
    localName: 'Dodo',
    description: 'Sweet, caramelized fried ripe plantain slices — the side dish that makes every Nigerian meal better.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['snacks', 'quick-meals', 'budget-friendly'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 5, cookTime: 10, servings: 2,
    estimatedCost: '₦300–500',
    ingredients: ['3 ripe plantains', 'Vegetable oil for frying', 'Pinch of salt (optional)'],
    instructions: ['Peel plantains and slice diagonally (about 1 cm thick).', 'Heat oil in a frying pan.', 'Fry plantain slices on medium heat until golden brown on each side.', 'Remove and drain on paper towels.', 'Serve alongside rice, beans, or as a standalone snack.'],
    tags: ['dodo', 'plantain', 'fried', 'side-dish', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Vendeuses_de_bananes_plantain.jpg/960px-Vendeuses_de_bananes_plantain.jpg',
    isFeatured: false, rating: 4.6,
  },
  {
    name: 'Dundun (Fried Yam)',
    localName: 'Dundun',
    description: 'Crispy fried yam sticks served with pepper sauce or egg sauce — a popular breakfast and street food.',
    countryId, countryName,
    region: 'Southwest (Yoruba) / Nationwide',
    categories: ['breakfast', 'street-food', 'snacks', 'budget-friendly'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 10, cookTime: 15, servings: 4,
    estimatedCost: '₦500–1,000',
    ingredients: ['1 medium yam tuber', 'Vegetable oil for frying', 'Salt', 'Pepper sauce or egg stew for dipping'],
    instructions: ['Peel yam and cut into thick sticks or rounds.', 'Soak in salted water for 5 minutes.', 'Heat oil in a deep pan.', 'Fry yam pieces in batches until golden brown and crispy.', 'Drain on paper towels.', 'Serve with fried egg sauce, pepper sauce, or fried stew.'],
    tags: ['dundun', 'fried-yam', 'yam', 'breakfast', 'street-food'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Vendeuses_de_bananes_plantain.jpg/960px-Vendeuses_de_bananes_plantain.jpg',
    isFeatured: false, rating: 4.5,
  },
  {
    name: 'Boli (Roasted Plantain)',
    localName: 'Boli',
    description: 'Charcoal-roasted plantain — smoky, sweet, and typically served with groundnut or pepper sauce. The roadside classic.',
    countryId, countryName,
    region: 'Southwest / Nationwide',
    categories: ['street-food', 'snacks', 'budget-friendly'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 5, cookTime: 15, servings: 2,
    estimatedCost: '₦200–500',
    ingredients: ['3 ripe plantains', 'Groundnut (roasted peanuts)', 'Pepper sauce', 'Palm oil (optional)'],
    instructions: ['Place whole unpeeled plantains directly on a charcoal grill.', 'Turn frequently until skin is blackened and flesh is soft throughout.', 'Peel and serve with roasted groundnuts and pepper sauce.', 'Optionally drizzle with palm oil.'],
    tags: ['boli', 'roasted-plantain', 'charcoal', 'street-food', 'groundnut'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Boli_and_Groundnut.png',
    isFeatured: false, rating: 4.6,
  },
  {
    name: 'Masa (Waina)',
    localName: 'Masa / Waina',
    description: 'Northern Nigerian rice cakes — slightly sour, spongy, and fried in a special round mould. Served with sugar, honey, or pepper soup.',
    countryId, countryName,
    region: 'North (Hausa)',
    categories: ['breakfast', 'snacks', 'street-food'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 480, cookTime: 20, servings: 6,
    estimatedCost: '₦500–1,000',
    ingredients: ['3 cups short-grain rice', '1/2 cup cooked rice (as starter)', '1 tsp yeast', '1/2 tsp sugar', 'Warm water', 'Pinch of salt', 'Vegetable oil'],
    instructions: ['Soak rice overnight. Drain.', 'Blend soaked rice with cooked rice and a little water to a smooth batter.', 'Add yeast and sugar. Mix well.', 'Cover and ferment for 6–8 hours (overnight is best).', 'When bubbly and slightly sour, add salt.', 'Heat a masa pan (or aebleskiver pan) with oil.', 'Pour batter into each mould. Cover and cook until set.', 'Flip and cook the other side until golden.', 'Serve with sugar, honey, or pepper soup.'],
    tags: ['masa', 'waina', 'rice-cake', 'northern', 'hausa'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Pizza_1_bg.jpg/960px-Pizza_1_bg.jpg',
    isFeatured: false, rating: 4.4,
  },
  {
    name: 'Kilishi',
    localName: 'Kilishi',
    description: 'Hausa dried meat — thinly sliced beef sun-dried and coated in a spicy groundnut paste. Nigeria\'s beef jerky.',
    countryId, countryName,
    region: 'North (Hausa)',
    categories: ['snacks', 'street-food', 'traditional'],
    targetAudience: ['young-professionals', 'everyone'],
    difficulty: 'hard',
    prepTime: 60, cookTime: 480, servings: 8,
    estimatedCost: '₦3,000–5,000',
    ingredients: ['1 kg beef (very lean)', '1 cup groundnut paste', '2 tbsp yaji spice', '1 tsp cayenne pepper', '1 tsp ginger powder', '1 tsp garlic powder', '1 onion (grated)', '1 tbsp honey', 'Salt'],
    instructions: ['Slice beef very thinly against the grain (paper-thin).', 'Spread on a mesh/rack and sun-dry for a full day.', 'Mix groundnut paste with all spices, honey, and a little water to form a marinade.', 'Dip each piece of dried meat into the paste, coating both sides.', 'Return to the drying rack and sun-dry again for another day.', 'Finally, grill briefly over low charcoal heat to toast.', 'Store in airtight container. Lasts for weeks.'],
    tags: ['kilishi', 'dried-meat', 'jerky', 'hausa', 'north', 'groundnut'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/%22Kilishi%22.JPG/960px-%22Kilishi%22.JPG',
    isFeatured: true, rating: 4.7,
  },

  // ═══════════════════════════════════════════════════════════════
  //  BEAN & PORRIDGE DISHES
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Ewa Agoyin (Mashed Beans)',
    localName: 'Ewa Agoyin',
    description: 'Soft, mashed honey beans drenched in fiery dried pepper sauce — a Yoruba street food legend.',
    countryId, countryName,
    region: 'Southwest (Yoruba)',
    categories: ['breakfast', 'street-food', 'budget-friendly'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 10, cookTime: 45, servings: 4,
    estimatedCost: '₦500–1,000',
    ingredients: ['2 cups honey beans', '1/2 cup palm oil (bleached)', '10 dried chilli peppers', '3 red bell peppers', '2 onions', '1 tbsp crayfish', 'Salt'],
    instructions: ['Boil beans until very soft and mashable.', 'Mash lightly with a wooden spoon (keep some texture).', 'For the sauce: bleach palm oil until clear.', 'Blend dried peppers and bell peppers.', 'Fry onions in the oil until blackened.', 'Add blended peppers and crayfish. Fry until oil floats.', 'Pour sauce generously over mashed beans.', 'Serve with bread or fried plantain.'],
    tags: ['ewa-agoyin', 'beans', 'mashed', 'street-food', 'yoruba', 'southwest'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Beans_and_fried_plantains_with_Beef02.jpg',
    isFeatured: true, rating: 4.7,
  },
  {
    name: 'Beans & Plantain (Ewa & Dodo)',
    localName: 'Ewa ati Dodo',
    description: 'The iconic Nigerian combo — stewed beans with fried plantain. Budget-friendly, filling, and delicious.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['lunch', 'dinner', 'budget-friendly'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 10, cookTime: 40, servings: 4,
    estimatedCost: '₦800–1,500',
    ingredients: ['2 cups brown beans', '3 ripe plantains', '1/2 cup palm oil', '2 red bell peppers', '2 scotch bonnet peppers', '1 onion', 'Crayfish', '2 seasoning cubes', 'Salt', 'Oil for frying'],
    instructions: ['Boil beans until tender (pressure cooker saves time).', 'Blend peppers and onion.', 'Add palm oil and blended pepper to the beans.', 'Add crayfish, seasoning, and salt. Simmer 15 minutes.', 'Peel and slice plantains. Fry until golden.', 'Serve beans in a bowl with fried plantain on the side.'],
    tags: ['beans', 'plantain', 'budget', 'student', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Mega_racimos_de_guineos.jpg/960px-Mega_racimos_de_guineos.jpg',
    isFeatured: false, rating: 4.5,
  },
  {
    name: 'Yam Porridge (Asaro)',
    localName: 'Asaro',
    description: 'Yoruba-style yam porridge — soft yam chunks in a rich, peppery palm oil sauce. Maximum comfort.',
    countryId, countryName,
    region: 'Southwest (Yoruba) / Nationwide',
    categories: ['lunch', 'dinner', 'traditional', 'budget-friendly'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 15, cookTime: 25, servings: 4,
    estimatedCost: '₦1,000–2,000',
    ingredients: ['1 medium yam tuber', '1/2 cup palm oil', '3 red bell peppers', '2 scotch bonnet peppers', '1 onion', '2 tbsp ground crayfish', '1 seasoning cube', 'Salt', 'Smoked fish (optional)'],
    instructions: ['Peel yam and cut into medium cubes.', 'Blend peppers and onion.', 'Boil yam cubes in water until half-cooked (about 10 minutes).', 'Add blended pepper, palm oil, crayfish, and seasoning.', 'Add smoked fish if using.', 'Cook until yam is very soft and sauce is thick.', 'Mash some pieces for creamier texture. Serve hot.'],
    tags: ['asaro', 'yam-porridge', 'yoruba', 'southwest', 'comfort'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Yam_pottage_or_%C3%80s%C3%A1r%C3%B3.jpg',
    isFeatured: false, rating: 4.5,
  },
  {
    name: 'Plantain Porridge',
    localName: 'Porridge Plantain',
    description: 'Unripe plantain cooked down in a savoury palm oil and pepper broth — hearty, filling, and nutritious.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['lunch', 'dinner', 'budget-friendly'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 10, cookTime: 25, servings: 4,
    estimatedCost: '₦800–1,500',
    ingredients: ['4 unripe plantains', '1/3 cup palm oil', '2 scotch bonnet peppers', '1 onion', '1 cup spinach or ugu', '2 tbsp crayfish', 'Smoked fish or stockfish', '1 seasoning cube', 'Salt'],
    instructions: ['Peel and cut plantains into chunks.', 'Boil in water until half-tender (about 10 minutes).', 'Add palm oil, blended pepper, onion, crayfish, and seasoning.', 'Add smoked fish. Continue cooking until plantain is soft.', 'Add chopped vegetables in the last 3 minutes.', 'Serve on its own or with rice.'],
    tags: ['plantain-porridge', 'unripe-plantain', 'budget', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Yam_pottage_or_%C3%80s%C3%A1r%C3%B3.jpg',
    isFeatured: false, rating: 4.4,
  },
  {
    name: 'Dan Wake',
    localName: 'Dan Wake',
    description: 'Northern Nigerian bean flour dumplings served with pepper sauce and oil — budget-friendly and filling.',
    countryId, countryName,
    region: 'North (Hausa)',
    categories: ['lunch', 'dinner', 'budget-friendly', 'street-food'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 15, cookTime: 15, servings: 4,
    estimatedCost: '₦300–600',
    ingredients: ['2 cups bean flour', '1 cup baobab (kuka) powder or cassava flour', 'Water', 'Potash (kanwa)', 'Palm oil or groundnut oil', 'Pepper sauce', 'Onion (sliced)', 'Salt'],
    instructions: ['Mix bean flour with kuka powder and a pinch of potash.', 'Add water gradually and knead into a smooth dough.', 'Pinch off small lumps and roll into balls.', 'Boil water in a pot. Drop balls into boiling water.', 'Cook until they float (about 10 minutes).', 'Drain and place in a bowl.', 'Drizzle with oil and pepper sauce. Add sliced onions.', 'Serve warm.'],
    tags: ['dan-wake', 'bean-dumplings', 'hausa', 'north', 'budget'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Hausa_Food_Dan_wake_01.jpg/960px-Hausa_Food_Dan_wake_01.jpg',
    isFeatured: false, rating: 4.3,
  },
  {
    name: 'Okpa',
    localName: 'Okpa',
    description: 'Steamed Bambara nut pudding from Enugu — protein-rich, smooth, and wrapped in banana leaves.',
    countryId, countryName,
    region: 'Southeast (Enugu / Nsukka)',
    categories: ['breakfast', 'snacks', 'budget-friendly'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 15, cookTime: 40, servings: 6,
    estimatedCost: '₦300–600',
    ingredients: ['3 cups okpa flour (Bambara nut flour)', '1/2 cup palm oil', '2 scotch bonnet peppers (blended)', '1 onion (grated)', '1 tsp ground crayfish', '1 seasoning cube', 'Salt', 'Banana leaves or nylon bags'],
    instructions: ['Mix okpa flour with warm water to a smooth batter.', 'Add palm oil, blended pepper, onion, crayfish, seasoning, and salt.', 'Mix thoroughly until well combined.', 'Pour into banana leaves or nylon bags. Tie securely.', 'Steam in a pot of boiling water for 40 minutes.', 'Check that it\'s firm when done.', 'Unwrap and serve warm with pap or on its own.'],
    tags: ['okpa', 'bambara-nut', 'steamed', 'enugu', 'southeast'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/83/Okpa_di_Oku.jpg',
    isFeatured: false, rating: 4.4,
  },

  // ═══════════════════════════════════════════════════════════════
  //  SPECIAL DISHES & DELICACIES
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Nkwobi',
    localName: 'Nkwobi',
    description: 'Igbo delicacy of spicy cow foot in a thick palm oil and utazi sauce — the king of Nigerian bar snacks.',
    countryId, countryName,
    region: 'Southeast (Igbo)',
    categories: ['snacks', 'dinner', 'traditional', 'festive'],
    targetAudience: ['young-professionals', 'everyone'],
    difficulty: 'medium',
    prepTime: 20, cookTime: 60, servings: 4,
    estimatedCost: '₦3,000–5,000',
    ingredients: ['1 kg cow foot (cut into pieces)', '1/2 cup palm oil', '3 tbsp potash (ngu/akanwu) dissolved in water', 'Scotch bonnet peppers', '1 tbsp ehuru (calabash nutmeg)', 'Ground crayfish', 'Utazi leaves', 'Ugba (oil bean) — optional', '2 seasoning cubes', 'Salt'],
    instructions: ['Boil cow foot with seasoning until very tender (pressure cooker recommended).', 'Mix palm oil with dissolved potash water and stir vigorously until it thickens and turns yellow.', 'Add ground ehuru, crayfish, and blended pepper to the palm oil mix.', 'Add the cooked cow foot. Toss to coat.', 'Adjust seasoning.', 'Garnish with sliced utazi leaves and ugba.', 'Serve in a wooden mortar bowl for the authentic experience.'],
    tags: ['nkwobi', 'cow-foot', 'igbo', 'southeast', 'bar-snack', 'palm-oil'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Nkwobi_made_with_Chevon.jpg',
    isFeatured: true, rating: 4.8,
  },
  {
    name: 'Isi Ewu (Goat Head)',
    localName: 'Isi Ewu',
    description: 'Igbo spiced goat head delicacy — tender meat in a creamy, peppery palm oil sauce with utazi leaves.',
    countryId, countryName,
    region: 'Southeast (Igbo)',
    categories: ['dinner', 'traditional', 'festive'],
    targetAudience: ['everyone'],
    difficulty: 'hard',
    prepTime: 30, cookTime: 90, servings: 6,
    estimatedCost: '₦4,000–7,000',
    ingredients: ['1 goat head (cleaned and cut)', '1/2 cup palm oil', '3 tbsp potash (ngu) dissolved in water', '2 tbsp ehuru (calabash nutmeg)', '3 scotch bonnet peppers', 'Ground crayfish', 'Utazi leaves', '2 seasoning cubes', 'Salt'],
    instructions: ['Clean goat head thoroughly. Cut into serving pieces.', 'Boil with onion and seasoning until very tender.', 'Mix palm oil with strained potash water. Stir until yellow and thick.', 'Add ehuru, crayfish, and blended pepper.', 'Add the tender goat head pieces. Mix well.', 'Simmer for 10 minutes to absorb flavours.', 'Garnish with thinly sliced utazi leaves.', 'Serve in a traditional wooden bowl.'],
    tags: ['isi-ewu', 'goat-head', 'igbo', 'southeast', 'delicacy'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Isi_ewu.jpg',
    isFeatured: true, rating: 4.7,
  },
  {
    name: 'Abacha (African Salad)',
    localName: 'Abacha',
    description: 'Igbo salad of dried shredded cassava in a potash-thickened palm oil dressing with ugba, garden egg, and crayfish.',
    countryId, countryName,
    region: 'Southeast (Igbo)',
    categories: ['snacks', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 30, cookTime: 10, servings: 4,
    estimatedCost: '₦1,500–3,000',
    ingredients: ['3 cups dried abacha (cassava flakes)', '1/2 cup palm oil', '2 tbsp potash (akanwu) in water', '1 cup ugba (oil bean seeds)', 'Garden egg leaves', '1 onion', '2 tbsp ground crayfish', 'Dry fish', 'Scotch bonnet peppers', 'Seasoning cube', 'Salt'],
    instructions: ['Soak abacha in warm water for 10 minutes. Drain.', 'Mix palm oil with strained potash water. Stir until thick and yellow.', 'Add crayfish, pepper, and seasoning to the palm oil mix.', 'Pour over the abacha and toss.', 'Add ugba, sliced onion, garden egg leaves, and dry fish.', 'Mix everything together gently.', 'Serve at room temperature.'],
    tags: ['abacha', 'african-salad', 'cassava', 'igbo', 'southeast'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/African_salad_mostly_prepared_by_the_southeastern_part_of_Nigeria_especially_in_the_eastern_part._This_meal_is_mostly_prepared_during_festive_seasons_like_new_yam_festival_or_marriage_ceremony.jpg',
    isFeatured: false, rating: 4.5,
  },
  {
    name: 'Dambu Nama (Shredded Meat)',
    localName: 'Dambu Nama',
    description: 'Northern Nigerian shredded dried meat — spiced, fluffy, and perfect as a snack or topping.',
    countryId, countryName,
    region: 'North (Hausa)',
    categories: ['snacks', 'traditional'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 20, cookTime: 120, servings: 6,
    estimatedCost: '₦2,000–3,500',
    ingredients: ['1 kg beef (lean cut)', '2 tbsp yaji spice', '1 onion', '2 cloves garlic', '1 tbsp ginger (grated)', '1 seasoning cube', 'Salt', '2 tbsp vegetable oil'],
    instructions: ['Boil beef with onion, garlic, ginger, and seasoning until very tender.', 'Drain and shred the meat into fine threads using two forks.', 'Spread shredded meat on a tray. Sun dry for a few hours (or oven dry at 150°F).', 'Heat oil in a pan. Add the dried shredded meat.', 'Add yaji spice and toss on low heat for 10 minutes.', 'The meat should be dry, fluffy, and golden.', 'Store in an airtight container. Lasts for weeks.'],
    tags: ['dambu-nama', 'shredded-meat', 'dried', 'hausa', 'north'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/%22Kilishi%22.JPG/960px-%22Kilishi%22.JPG',
    isFeatured: false, rating: 4.4,
  },
  {
    name: 'Fura da Nono',
    localName: 'Fura da Nono',
    description: 'Northern Nigerian milkshake — millet balls crumbled into fermented milk (nono). Refreshing and nutritious.',
    countryId, countryName,
    region: 'North (Hausa / Fulani)',
    categories: ['beverages', 'breakfast', 'snacks', 'street-food'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 30, cookTime: 30, servings: 4,
    estimatedCost: '₦300–500',
    ingredients: ['2 cups millet', '1 tsp ginger (dry, ground)', '1 tsp cloves (ground)', '1 tsp black pepper (ground)', 'Sugar or honey', '1 litre nono (fermented milk / yoghurt)'],
    instructions: ['Wash and soak millet for a few hours. Drain.', 'Grind millet with ginger, cloves, and black pepper into a paste.', 'Form into balls and boil in water until cooked through (20 min).', 'Remove and let cool.', 'Crumble fura balls into a bowl of cold nono.', 'Add sugar or honey to taste.', 'Mix well and drink cold. Incredibly refreshing.'],
    tags: ['fura', 'nono', 'millet', 'fermented-milk', 'fulani', 'north'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Kosai_Da_kunun_Gyada.jpg',
    isFeatured: false, rating: 4.5,
  },

  // ═══════════════════════════════════════════════════════════════
  //  BEVERAGES
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Zobo (Hibiscus Drink)',
    localName: 'Zobo',
    description: 'Deep-red hibiscus flower drink — sweet, tart, and spiced with ginger and cloves. Nigeria\'s favourite homemade juice.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['beverages'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 10, cookTime: 30, servings: 8,
    estimatedCost: '₦500–800',
    ingredients: ['3 cups dried hibiscus flowers (zobo leaves)', '1 large ginger root (sliced)', '1 fresh pineapple (diced)', '6 whole cloves', '1 cinnamon stick', 'Sugar or honey to taste', '8 cups water'],
    instructions: ['Rinse zobo leaves to remove dirt.', 'Add to a pot with water, ginger, cloves, and cinnamon.', 'Boil for 20–30 minutes until deep red.', 'Strain into a large jug.', 'Blend pineapple and strain the juice into the zobo.', 'Add sugar or honey to taste.', 'Refrigerate until ice cold.', 'Serve over ice. Add diced fruit for garnish.'],
    tags: ['zobo', 'hibiscus', 'drink', 'juice', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Sobolo.jpg/960px-Sobolo.jpg',
    isFeatured: true, rating: 4.8,
  },
  {
    name: 'Kunu (Millet Drink)',
    localName: 'Kunun Zaki',
    description: 'Sweet, milky millet drink spiced with ginger and cloves — a Northern Nigerian refresher served cold or at room temperature.',
    countryId, countryName,
    region: 'North (Hausa) / Nationwide',
    categories: ['beverages', 'breakfast'],
    targetAudience: ['everyone'],
    difficulty: 'medium',
    prepTime: 480, cookTime: 30, servings: 6,
    estimatedCost: '₦400–700',
    ingredients: ['2 cups millet', '1 cup rice', '2 tbsp ginger (sliced)', '1 tbsp cloves', '1 cinnamon stick', 'Sugar to taste', 'Water'],
    instructions: ['Soak millet and rice together overnight.', 'Drain and blend with ginger, cloves, and a little water.', 'Divide paste into two: mix half with boiling water (to cook it).', 'Mix the cooked portion back with the raw portion.', 'Add sugar and more water to desired consistency.', 'Sieve through a fine mesh.', 'Chill and serve cold.'],
    tags: ['kunu', 'kunun-zaki', 'millet', 'drink', 'hausa', 'north'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Lapin_blanc.jpg/960px-Lapin_blanc.jpg',
    isFeatured: false, rating: 4.4,
  },
  {
    name: 'Chapman',
    localName: 'Chapman',
    description: 'Nigeria\'s signature cocktail (non-alcoholic version) — a fizzy, fruity mix of Fanta, Sprite, grenadine, and bitters with cucumber and orange.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['beverages'],
    targetAudience: ['university-students', 'young-professionals', 'everyone'],
    difficulty: 'easy',
    prepTime: 10, cookTime: 0, servings: 4,
    estimatedCost: '₦1,000–1,500',
    ingredients: ['1 bottle Fanta (orange soda)', '1 bottle Sprite (lemon-lime soda)', '2 tbsp grenadine syrup', '1 tsp Angostura bitters', '1 fresh orange (sliced)', '1 cucumber (sliced)', '1 lemon/lime (juiced)', 'Ice cubes', 'Ribena (blackcurrant syrup) — optional'],
    instructions: ['In a large pitcher, combine Fanta and Sprite.', 'Add grenadine syrup and Angostura bitters.', 'Squeeze in lemon juice.', 'Add orange and cucumber slices.', 'Stir gently.', 'Add Ribena for deeper colour (optional).', 'Serve over plenty of ice in tall glasses.', 'Garnish with cucumber and orange slices.'],
    tags: ['chapman', 'cocktail', 'non-alcoholic', 'party', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Chapman_in_a_punch_bowl.jpg',
    isFeatured: true, rating: 4.7,
  },
  {
    name: 'Pap (Ogi / Akamu)',
    localName: 'Ogi / Akamu',
    description: 'Fermented corn porridge — smooth, tangy, and comforting. The classic Nigerian breakfast, usually paired with akara or moi moi.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['breakfast', 'beverages', 'budget-friendly'],
    targetAudience: ['university-students', 'everyone'],
    difficulty: 'easy',
    prepTime: 5, cookTime: 10, servings: 2,
    estimatedCost: '₦100–300',
    ingredients: ['1 cup ogi (fermented corn paste)', 'Boiling water', 'Sugar or honey', 'Milk (evaporated or condensed) — optional'],
    instructions: ['Dissolve ogi paste in a cup with cold water until smooth.', 'Bring water to a rolling boil.', 'Pour boiling water into the ogi mixture while stirring continuously.', 'Stir vigorously — it will thicken and become translucent.', 'Add sugar/honey and milk to taste.', 'Serve warm with akara, moi moi, or bread.'],
    tags: ['pap', 'ogi', 'akamu', 'corn', 'breakfast', 'fermented', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Ogi%3BPap.jpg/960px-Ogi%3BPap.jpg',
    isFeatured: false, rating: 4.3,
  },

  // ═══════════════════════════════════════════════════════════════
  //  MORE PROTEIN DISHES
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Peppered Snail',
    localName: 'Peppered Snail',
    description: 'Juicy giant African land snails sautéed in a fiery pepper and onion sauce — a hugely popular bar centre delicacy.',
    countryId, countryName,
    region: 'Southwest / Southeast',
    categories: ['snacks', 'dinner', 'traditional'],
    targetAudience: ['young-professionals', 'everyone'],
    difficulty: 'medium',
    prepTime: 30, cookTime: 25, servings: 4,
    estimatedCost: '₦3,000–5,000',
    ingredients: ['10 giant snails', '4 scotch bonnet peppers', '3 red bell peppers', '2 onions', '2 tbsp vegetable oil', '1 tbsp ground crayfish', '1 seasoning cube', 'Salt', 'Lime juice'],
    instructions: ['Clean snails with lime and alum. Wash thoroughly.', 'Boil snails with onion and seasoning until tender (30 min).', 'Blend scotch bonnet and bell peppers coarsely.', 'Heat oil. Fry diced onions.', 'Add blended pepper and fry until reduced.', 'Add crayfish, seasoning, and salt.', 'Add cooked snails. Toss to coat.', 'Simmer 5 minutes. Serve hot.'],
    tags: ['snail', 'peppered', 'bar-food', 'southwest', 'delicacy'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Peppered_and_Vegetable_Snails.jpg/960px-Peppered_and_Vegetable_Snails.jpg',
    isFeatured: false, rating: 4.6,
  },
  {
    name: 'Peppered Gizzard',
    localName: 'Peppered Gizzard',
    description: 'Tender chicken gizzards in a spicy bell pepper sauce — a popular small chop and bar snack.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['snacks', 'street-food'],
    targetAudience: ['everyone'],
    difficulty: 'easy',
    prepTime: 10, cookTime: 30, servings: 4,
    estimatedCost: '₦1,500–2,500',
    ingredients: ['500 g chicken gizzards', '3 red bell peppers', '2 scotch bonnet peppers', '2 onions', '2 tbsp vegetable oil', '1 tsp curry powder', '1 tsp thyme', '1 seasoning cube', 'Salt'],
    instructions: ['Boil gizzards with onion, curry, thyme, and seasoning until tender.', 'Dice bell peppers and onions.', 'Heat oil. Fry onions until golden.', 'Add diced pepper and blended scotch bonnet. Fry 5 minutes.', 'Add cooked gizzards and toss.', 'Season to taste. Cook 5 more minutes.', 'Serve as a snack, small chop, or side dish.'],
    tags: ['gizzard', 'peppered', 'small-chops', 'snack', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Gizzard_of_Chicken.JPG/960px-Gizzard_of_Chicken.JPG',
    isFeatured: false, rating: 4.5,
  },
  {
    name: 'Nigerian Chicken Stew',
    localName: 'Obe Ata / Tomato Stew',
    description: 'Base of Nigerian cooking — rich, fried tomato and pepper stew with chicken. Goes on everything from rice to yam to bread.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['lunch', 'dinner', 'traditional'],
    targetAudience: ['university-students', 'young-professionals', 'everyone'],
    difficulty: 'medium',
    prepTime: 20, cookTime: 45, servings: 6,
    estimatedCost: '₦3,000–5,000',
    ingredients: ['1 whole chicken (cut into pieces)', '8 tomatoes', '4 red bell peppers (tatashe)', '4 scotch bonnet peppers', '3 onions', '1 cup vegetable oil', '2 tbsp tomato paste', '2 tsp curry powder', '1 tsp thyme', '2 bay leaves', '2 seasoning cubes', 'Salt'],
    instructions: ['Season chicken with thyme, curry, seasoning, onion, and salt. Boil until tender.', 'Fry chicken pieces in oil until golden. Set aside.', 'Blend tomatoes, tatashe, scotch bonnet, and 1 onion.', 'In the same oil, fry chopped onion. Add tomato paste.', 'Pour in blended pepper mix. Fry on medium heat until oil floats (~30 min). This is the key step.', 'Add bay leaves, curry, thyme, chicken stock, and chicken pieces.', 'Simmer for 15 minutes.', 'Serve over rice, yam, plantain, or with bread.'],
    tags: ['stew', 'tomato', 'chicken', 'obe-ata', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Red_pepper_and_tomato_soup%2C_with_chicken%2C_wild_rice%2C_and_black_pepper_-_Massachusetts.jpg/960px-Red_pepper_and_tomato_soup%2C_with_chicken%2C_wild_rice%2C_and_black_pepper_-_Massachusetts.jpg',
    isFeatured: true, rating: 4.8,
  },
  {
    name: 'Gizdodo',
    localName: 'Gizdodo',
    description: 'Gizzard + dodo combo — fried plantain and spiced gizzard tossed in a pepper sauce. A modern Nigerian party favourite.',
    countryId, countryName,
    region: 'Southwest / Nationwide',
    categories: ['snacks', 'dinner', 'quick-meals'],
    targetAudience: ['young-professionals', 'everyone'],
    difficulty: 'easy',
    prepTime: 15, cookTime: 25, servings: 4,
    estimatedCost: '₦2,000–3,000',
    ingredients: ['500 g chicken gizzards', '3 ripe plantains', '3 red bell peppers', '2 scotch bonnet peppers', '1 large onion', '2 tbsp vegetable oil', '1 tsp curry', '1 tsp thyme', '1 seasoning cube', 'Salt', 'Oil for frying'],
    instructions: ['Boil gizzards with seasoning until tender. Cut into halves.', 'Peel and slice plantains. Fry until golden. Set aside.', 'Dice bell pepper and onion.', 'Heat oil. Fry onions, add diced peppers and blended scotch bonnet.', 'Add gizzards, curry, thyme, and seasoning. Toss well.', 'Fold in the fried plantain gently.', 'Serve hot as a side dish or small chop.'],
    tags: ['gizdodo', 'gizzard', 'plantain', 'modern', 'party'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/43/Chinwe_Uzoma_kitchen_%26_Lifestyle_-_How_to_make_gizdodo_-_This_is_so_GOOD%21%21%21_Chinwe_Uzoma_Kitchen_%26_Lifestyle.png',
    isFeatured: false, rating: 4.6,
  },

  // ═══════════════════════════════════════════════════════════════
  //  BREAKFAST / QUICK MEALS
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Indomie Jollof',
    localName: 'Indomie',
    description: 'Nigerian-style instant noodles fried with vegetables, egg, and spices — the ultimate student survival meal.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['quick-meals', 'budget-friendly', 'dinner'],
    targetAudience: ['university-students'],
    difficulty: 'easy',
    prepTime: 5, cookTime: 10, servings: 1,
    estimatedCost: '₦300–500',
    ingredients: ['1 pack Indomie noodles', '1 egg', '1 small onion', '1 small tomato (diced)', '1 green pepper (diced)', 'Vegetable oil', 'Seasoning from the pack', 'Scotch bonnet (optional)'],
    instructions: ['Boil noodles for 2 minutes. Drain most of the water.', 'Heat oil in a pan. Fry onion and tomato.', 'Add diced pepper and optional scotch bonnet.', 'Add the noodles and seasoning packet. Stir fry.', 'Push noodles aside. Crack egg into the pan and scramble.', 'Mix everything together. Serve immediately.'],
    tags: ['indomie', 'noodles', 'student', 'quick', 'budget', 'nationwide'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Indomie_Logo.png',
    isFeatured: false, rating: 4.3,
  },
  {
    name: 'Bread & Egg',
    localName: 'Bread & Egg Sauce',
    description: 'Agege bread with fried egg stew — the quintessential quick Nigerian breakfast for busy mornings.',
    countryId, countryName,
    region: 'Nationwide',
    categories: ['breakfast', 'quick-meals', 'budget-friendly'],
    targetAudience: ['university-students', 'young-professionals'],
    difficulty: 'easy',
    prepTime: 5, cookTime: 10, servings: 2,
    estimatedCost: '₦300–500',
    ingredients: ['1 loaf Agege bread', '4 eggs', '2 tomatoes', '1 onion', '1 scotch bonnet pepper', '2 tbsp vegetable oil', '1 seasoning cube', 'Salt'],
    instructions: ['Dice tomatoes, onion, and pepper.', 'Heat oil. Fry onions until soft.', 'Add tomatoes and pepper. Fry until reduced.', 'Add seasoning and salt.', 'Crack eggs directly into the sauce. Stir to scramble in the sauce.', 'Cook until eggs are set.', 'Serve in thick slices of warm Agege bread.'],
    tags: ['bread', 'egg', 'agege', 'breakfast', 'quick', 'budget'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/SuyavarietiesTX.JPG/960px-SuyavarietiesTX.JPG',
    isFeatured: false, rating: 4.4,
  },
];

// ─── Seeder logic ──────────────────────────────────────────────
export const seedNigerianFoods = async () => {
  const nigeria = await getNigeriaId();
  console.log(`  📍 Nigeria found: ${nigeria.id}`);

  const collectionRef = db.collection(COLLECTIONS.FOODS);

  // Delete existing Nigerian foods only
  const existing = await collectionRef.where('countryId', '==', nigeria.id).get();
  if (!existing.empty) {
    const BATCH_SIZE = 500;
    for (let i = 0; i < existing.docs.length; i += BATCH_SIZE) {
      const batch = db.batch();
      existing.docs.slice(i, i + BATCH_SIZE).forEach((doc) => batch.delete(doc.ref));
      await batch.commit();
    }
    console.log(`  🗑️  Cleared ${existing.size} existing Nigerian foods`);
  }

  const foodsData = makeFoods(nigeria.id, nigeria.name);

  // Insert in batches
  const BATCH_SIZE = 500;
  const results = [];
  for (let i = 0; i < foodsData.length; i += BATCH_SIZE) {
    const batch = db.batch();
    const chunk = foodsData.slice(i, i + BATCH_SIZE);
    for (const data of chunk) {
      const formatted = formatFood(data);
      const docRef = collectionRef.doc();
      batch.set(docRef, formatted);
      results.push({ id: docRef.id, ...formatted });
    }
    await batch.commit();
  }

  // Update food count on Nigeria
  const countryRef = db.collection(COLLECTIONS.COUNTRIES).doc(nigeria.id);
  await countryRef.update({ foodCount: results.length });

  return results;
};

// ─── Run standalone ────────────────────────────────────────────
const isMainModule = process.argv[1]?.replace(/\\/g, '/').endsWith('seedNigerianFoods.js');

if (isMainModule) {
  console.log('🇳🇬 Seeding Nigerian foods…\n');
  seedNigerianFoods()
    .then((foods) => {
      console.log(`\n✅ Seeded ${foods.length} Nigerian foods!`);
      console.log('\nFoods seeded:');
      foods.forEach((f, i) => console.log(`  ${i + 1}. ${f.name} — ${f.region}`));
      process.exit(0);
    })
    .catch((err) => {
      console.error('❌ Error:', err.message);
      process.exit(1);
    });
}
